#!/bin/bash

# ========================= static configuration
# name of this script
CONFIGEXEC="configure_cvc4_local"
# the directory containing source trees $HOMEDIR/cvc4-*
HOMEDIR="/home/andrew"
# the directory containing the local build file structure
BASEBUILDDIR="$HOMEDIR/build-cvc4"
# ========================= end static configuration

# usage: $CONFIGEXEC [build type]
echo "=== $CONFIGEXEC $@"

# to be run in source directory $HOMEDIR/cvc4-*/. AU

BUILDTYPE=$1
shift

# ========================= compute source suffix
CURRDIR=$(pwd)
BASEDIR="$HOMEDIR/cvc4"
echo "rexec: This directory is $CURRDIR"
if [[ $CURRDIR != $BASEDIR* ]]; then
  echo "rexec: ERROR: not a git root directory"
  exit 1;
fi
SRCSUFFIX=${CURRDIR#"$BASEDIR"}
if [ ! -z $SRCSUFFIX ]; then
  SRCSUFFIX=${SRCSUFFIX#"-"}
fi
echo "rexec: with directory suffix \"$SRCSUFFIX\""
# ========================= end compute source suffix


# ========================= compute build directory
if [ ! -z $SRCSUFFIX ]; then
  BUILDDIR="$BASEBUILDDIR/$SRCSUFFIX/$BUILDTYPE/"
else
  BUILDDIR="$BASEBUILDDIR/$BUILDTYPE/"
fi
echo "lexec_lnx: build directory is $BUILDDIR"
# ========================= end compute build directory

# ========================= compute configure

if [ $BUILDTYPE = "prod" ]; then
  CARGS="production --static --program-prefix="
elif [ $BUILDTYPE = "debug" ]; then
  CARGS="debug --static --no-unit-testing --program-prefix=d-"
elif [ $BUILDTYPE = "debug-unit" ]; then
  CARGS="debug --program-prefix=du-"
elif [ $BUILDTYPE = "profile" ]; then
  CARGS="production --static --profiling --program-prefix=prof-"
else
  echo "$CONFIGEXEC: ERROR: unknown build type $BUILDTYPE"
  exit 1
fi
if [ -z $SRCPREFIX ]; then
  CARGS="$CARGS"
else
  CARGS="$CARGS$SRCPREFIX-"
fi
# ========================= end compute configure


CARGS="$CARGS --name=$BUILDDIR --prefix=$HOMEDIR/ --tracing --cxxtest-dir=$HOMEDIR/cxxtest/ --symfpu $@"
echo "$CONFIGEXEC: EXEC: ./configure.sh $CARGS"
./configure.sh $CARGS

